Repository googleapis/google-api-nodejs-client, pull requests merged in 2018-09, with the labels that each got.

#1306 Add synth.py for automating client library generation
  synth.py
Labels: cla: yes, in progress

#1320 Retry npm install in CI
  .circleci/config.yml
  .circleci/npm-install-retry.js
Labels: cla: yes, in progress

#1285 fix: add better error handling around sample client and redirect URIs
  samples/sampleclient.js
Labels: cla: yes, in progress

#1313 fix: upgrade to the latest google-auth-library
  package.json
  test/test.auth.ts
Labels: cla: yes, in progress

#1321 Use synth templating and update CI
  .appveyor.yml
  .circleci/config.yml
  .eslintignore
  .eslintrc.yml
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .jsdoc.js
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/docs.cfg
  .kokoro/continuous/node8/lint.cfg
  .kokoro/continuous/node8/samples-test.cfg
  .kokoro/continuous/node8/system-test.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/docs.cfg
  .kokoro/presubmit/node8/lint.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/presubmit/windows/common.cfg
  .kokoro/presubmit/windows/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.bat
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .nycrc
  Makefile
  package.json
  samples/package.json
  synth.py
Labels: cla: yes, in progress, kokoro:force-run

#1323 Fix samples tests
  package.json
  samples/package.json
  test/samples/test.samples.drive.ts
  test/samples/test.samples.youtube.ts
  test/test.kitchen.ts
Labels: cla: yes, in progress

#1331 Remove reference docs
  README.md
  package.json
  samples/README.md
Labels: cla: yes

#1333 Add statement of support to readme
  README.md
Labels: cla: yes

#1338 Fix error handling in batchGet sample
  samples/analyticsReporting/batchGet.js
Labels: cla: yes

#1340 Enable no-var in eslint
  .eslintrc.yml
Labels: cla: yes, in progress

#1342 docs: replace google/ with googleapis/ in URIs
  README.md
Labels: cla: yes, in progress

#1343 Make npm install timeout configurable
  .circleci/npm-install-retry.js
Labels: cla: yes, in progress

#1344 Fix the sample tests
  samples/sampleclient.js
Labels: cla: yes, in progress

#1345 docs: fix generator script path
  .github/CONTRIBUTING.md
Labels: cla: yes

#1347 Enable prefer-const in the eslint config
  .eslintrc.yml
Labels: cla: yes, in progress

#1350 Do not generate libraries with synth
  synth.py
Labels: cla: yes

#1357 test: remove appveyor config
  .appveyor.yml
Labels: cla: yes, in progress

#1355 docs: add supported versions of node.js to the readme
  README.md
Labels: cla: yes, in progress

#1360 Release googleapis v34.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: cla: yes, in progress

#1361 fix: update gsuite admin samples
  README.md
  samples/defaultauth.js
  samples/directory_v1/README.md
  samples/directory_v1/authData.json
  samples/directory_v1/group-delete.js
  samples/directory_v1/group-email-delete.js
  samples/directory_v1/group-email-insert.js
  samples/directory_v1/group-insert.js
Labels: cla: yes, in progress

#1364 Don't publish sourcemaps
  package.json
Labels: cla: yes, in progress

#1366 fix(tests): Fix samples test
  samples/drive/download.js
  samples/drive/upload.js
Labels: cla: yes, in progress, kokoro:force-run

#1365 Fix Kokoro builds
  package.json
  samples/drive/download.js
  samples/drive/upload.js
  samples/youtube/upload.js
  system-test/kitchen.test.ts
  test/test.media.ts
  tsconfig.json
Labels: cla: yes, in progress
