Repository googleapis/google-api-nodejs-client, pull requests merged in 2019-07, with the labels that each got.

#1735 chore: release 40.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: :rotating_light:, autorelease: pending, cla: yes, type: process

#1757 fix: don't replace '.' with '_' in interface
  src/apis/adexchangebuyer/v1.2.ts
  src/apis/adexchangebuyer/v1.3.ts
  src/apis/adexchangebuyer/v1.4.ts
  src/apis/adsense/v1.4.ts
  src/apis/adsensehost/v4.1.ts
  src/apis/analytics/v2.4.ts
  src/apis/analyticsreporting/v4.ts
  src/apis/androidpublisher/v1.1.ts
  src/apis/bigquery/v2.ts
  src/apis/content/v2.1.ts
  src/apis/dfareporting/v3.1.ts
  src/apis/dfareporting/v3.2.ts
  src/apis/dfareporting/v3.3.ts
  src/apis/fcm/v1.ts
  src/apis/iam/v1.ts
  src/apis/iap/v1beta1.ts
  src/apis/pubsub/v1.ts
  src/apis/pubsub/v1beta2.ts
  src/apis/runtimeconfig/v1beta1.ts
  src/apis/servicemanagement/v1.ts
  src/generator/templates/api-endpoint.njk
Labels: cla: yes

#1760 chore: release 41.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#1761 fix(docs): switch to googleapis.dev link for reference docs
  README.md
Labels: cla: yes

#1731 docs(samples): add google docs samples
  samples/docs/create.js
  samples/docs/get.js
  test/samples/test.samples.docs.ts
Labels: cla: yes

#1763 chore: release 41.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#1765 docs: update docs and samples for drive export
  README.md
  samples/drive/export.js
  test/samples/test.samples.drive.ts
Labels: cla: yes

#1769 refactor(auth)!: pulling in updated idempotent google-auth-library
  README.md
  package.json
  samples/defaultauth.js
  samples/drive/download.js
  samples/jwt.js
  samples/oauth2.js
  src/googleapis.ts
  system-test/auth.test.ts
Labels: cla: yes

#1780 fix(deps): pull in version of gts that does not OOM error
  package.json
  test/samples/test.compute.samples.ts
Labels: cla: yes

#1781 docs: use the jsdoc-fresh theme
  .jsdoc.js
Labels: cla: yes

#1778 chore: release 42.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, status: blocked, type: process
