Repository googleapis/google-api-nodejs-client, pull requests merged in 2019-05, with the labels that each got.

#1690 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#1691 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#1692 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#1696 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#1697 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: automerge, cla: yes

#1698 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#1694 build: switches to piping coverage to codecov from Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#1704 refactor: drop pify dependency
  package.json
  system-test/kitchen.test.ts
  test/samples/test.samples.auth.ts
  test/test.media.ts
Labels: cla: yes

#1706 fix: Incorrect case README
  README.md
Labels: cla: yes

#1707 build: nyc configuration with --all
  .nycrc
  synth.metadata
Labels: cla: yes

#1710 chore: release 40.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#1708 NodeJS Chat Example
  src/apis/chat/README.md
Labels: cla: yes

#1715 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#1717 build: add configuration for automated doc deployemnt
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#1720 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#1684 docs(samples): add sample for insertColumn
  samples/sheets/insert-column.js
Labels: cla: yes

#1722 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
