Repository googleapis/google-api-nodejs-client, pull requests merged in 2019-04, with the labels that each got.

#1669 Release googleapis v39.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#1677 docs: document export as alternative to get
  samples/drive/download.js
Labels: cla: yes, type: docs

#1676 fix(samples): fix readline args in youtube upload
  samples/youtube/upload.js
Labels: automerge, cla: yes

#1687 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes
