Repository googleapis/google-api-nodejs-client, pull requests merged in 2019-02, with the labels that each got.

#1573 fix: respect `.` in api versions (fix adsense API)
  src/apis/adexchangebuyer/index.ts
  src/apis/adsense/index.ts
  src/apis/adsensehost/index.ts
  src/apis/analytics/index.ts
  src/apis/androidpublisher/index.ts
  src/apis/content/index.ts
  src/apis/dfareporting/index.ts
  src/generator/templates/api-index.njk
  test/test.clients.ts
Labels: automerge, cla: yes

#1581 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#1585 Release googleapis v37.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#1583 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#1589 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes

#1592 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#1599 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#1601 Use people API instead of plus API
  samples/people/me.js
Labels: automerge, cla: yes

#1603 docs: update CONTRIBUTING link
  README.md
Labels: cla: yes

#1602 fix: correct types param name for media mime-type
  src/generator/templates/api-endpoint.njk
  src/generator/templates/resource-partial.njk
Labels: cla: yes

#1596 build: use linkinator for docs test
  package.json
Labels: cla: yes

#1607 docs: Remove "releasing" ToC from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: automerge, cla: yes

#1615 docs: update contributing guide
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes
