Repository googleapis/google-api-nodejs-client, pull requests merged in 2019-06, with the labels that each got.

#1727 docs: Don't repeat ourselves with the API list
  README.md
Labels: cla: yes

#1728 docs: generate docs for dfareporting and add repo-metadata
  .gitignore
  .repo-metadata.json
  package.json
  samples/README.md
  src/generator/docs.ts
Labels: cla: yes

#1734 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
Labels: cla: yes

#1737 build: use c8 for coverage
  package.json
Labels: cla: yes

#1747 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
Labels: cla: yes

#1739 fix(deps): explicitly update google-apis-common to latest
  package.json
Labels: :rotating_light:, automerge, cla: yes

#1743 build: switch to magic proxy for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: :rotating_light:, cla: yes

#1748 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes

#1745 docs: fixes options section anchor link
  README.md
Labels: cla: yes
