Repository googleapis/google-api-nodejs-client, pull requests merged in 2020-05, with the labels that each got.

#2075 test: update kitchen test tsc
  package.json
  system-test/kitchen.test.ts
  test/fixtures/kitchen/package.json
  test/fixtures/kitchen/tsconfig.json
Labels: cla: yes

#2078 refactor: use yargs-parser
  package.json
  src/generator/download.ts
  src/generator/generate.ts
Labels: cla: yes

#2079 build: format code before written
  .eslintignore
  .prettierignore
  package.json
  src/generator/generator.ts
  synth.py
  test/test.clients.ts
Labels: cla: yes

#2081 feat!: run the generator
  discovery/acceleratedmobilepageurl-v1.json
  discovery/adexchangebuyer2-v2beta1.json
  discovery/admob-v1.json
  discovery/adsense-v1.4.json
  discovery/adsensehost-v4.1.json
  discovery/alertcenter-v1beta1.json
  discovery/androiddeviceprovisioning-v1.json
  discovery/androidmanagement-v1.json
  discovery/binaryauthorization-v1.json
  discovery/binaryauthorization-v1beta1.json
  discovery/blogger-v2.json
  discovery/blogger-v3.json
  discovery/classroom-v1.json
  discovery/cloudbilling-v1.json
  discovery/cloudsearch-v1.json
  discovery/cloudshell-v1.json
  discovery/cloudshell-v1alpha1.json
  discovery/containeranalysis-v1beta1.json
  discovery/digitalassetlinks-v1.json
  discovery/dlp-v2.json
  discovery/docs-v1.json
  discovery/domainsrdap-v1.json
  discovery/factchecktools-v1alpha1.json
  discovery/firebase-v1beta1.json
  discovery/firebasedynamiclinks-v1.json
  discovery/firebasehosting-v1beta1.json
  discovery/firebaseml-v1beta2.json
  discovery/gameservices-v1beta.json
  discovery/jobs-v2.json
  discovery/libraryagent-v1.json
  discovery/manufacturers-v1.json
  discovery/prod_tt_sasportal-v1alpha1.json
  discovery/safebrowsing-v4.json
  discovery/sasportal-v1alpha1.json
  discovery/script-v1.json
  discovery/searchconsole-v1.json
  discovery/sheets-v4.json
  discovery/slides-v1.json
  discovery/streetviewpublish-v1.json
  discovery/youtubeAnalytics-v1.json
  discovery/youtubeAnalytics-v2.json
  discovery/youtubereporting-v1.json
  src/apis/binaryauthorization/v1.ts
  src/apis/binaryauthorization/v1beta1.ts
  src/apis/cloudbilling/v1.ts
  src/apis/cloudsearch/v1.ts
  src/apis/cloudshell/v1alpha1.ts
  src/apis/containeranalysis/v1beta1.ts
  src/apis/dialogflow/index.ts
  src/apis/dialogflow/v2beta1.ts
  src/apis/docs/index.ts
  src/apis/docs/v1.ts
  src/apis/firebasehosting/v1beta1.ts
  src/generator/generator.ts
  src/index.ts
Labels: cla: yes

#2084 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#2088 build: address nightly regen failures
  package.json
  src/generator/synth.ts
Labels: cla: yes

#2092 build: use synthtool for nightly generation
  .github/workflows/generator.yaml
  src/generator/synth.ts
  synth.py
Labels: cla: yes

#2097 build: npm i is required to generate
  synth.py
Labels: automerge, cla: yes

#2100 build: ignore revision-only updates
  src/generator/download.ts
  test/test.download.ts
  test/test.samplegen.ts
Labels: cla: yes

#2104 feat!: run the generator
  discovery/apigee-v1.json
  discovery/bigqueryreservation-v1.json
  discovery/bigqueryreservation-v1alpha2.json
  discovery/bigqueryreservation-v1beta1.json
  discovery/cloudsearch-v1.json
  discovery/container-v1.json
  discovery/datastore-v1.json
  discovery/datastore-v1beta3.json
  discovery/dialogflow-v2.json
  discovery/dialogflow-v2beta1.json
  discovery/file-v1.json
  discovery/file-v1beta1.json
  discovery/firebase-v1beta1.json
  discovery/firebasehosting-v1beta1.json
  discovery/gamesManagement-v1management.json
  discovery/jobs-v3.json
  discovery/monitoring-v3.json
  discovery/people-v1.json
  discovery/pubsub-v1.json
  discovery/secretmanager-v1.json
  discovery/secretmanager-v1beta1.json
  discovery/testing-v1.json
  discovery/toolresults-v1beta3.json
  src/apis/bigqueryreservation/v1.ts
  src/apis/bigqueryreservation/v1beta1.ts
  src/apis/cloudsearch/v1.ts
  src/apis/container/v1.ts
  src/apis/datastore/v1.ts
  src/apis/datastore/v1beta3.ts
  src/apis/dialogflow/v2.ts
  src/apis/dialogflow/v2beta1.ts
  src/apis/file/v1.ts
  src/apis/file/v1beta1.ts
  src/apis/firebase/v1beta1.ts
  src/apis/firebasehosting/v1beta1.ts
  src/apis/gamesManagement/v1management.ts
  src/apis/jobs/v3.ts
  src/apis/monitoring/v3.ts
  src/apis/people/v1.ts
  src/apis/pubsub/v1.ts
  src/apis/secretmanager/v1.ts
  src/apis/secretmanager/v1beta1.ts
  src/apis/testing/v1.ts
  src/apis/toolresults/v1beta3.ts
  synth.metadata
Labels: cla: yes, context: partial

#2106 build: track changes in the discovery file
  src/generator/download.ts
  src/generator/generator.ts
  test/test.download.ts
Labels: cla: yes

#2117 build: fix mysterious await failure
  package.json
  src/generator/download.ts
  test/test.generator.ts
Labels: cla: yes

#2122 feat!: run the generator
  discovery/appengine-v1.json
  discovery/appengine-v1beta.json
  discovery/binaryauthorization-v1.json
  discovery/cloudidentity-v1beta1.json
  discovery/cloudkms-v1.json
  discovery/composer-v1beta1.json
  discovery/content-v2.1.json
  discovery/dfareporting-v3.3.json
  discovery/dfareporting-v3.4.json
  discovery/displayvideo-v1.json
  discovery/gamesConfiguration-v1configuration.json
  discovery/gamesManagement-v1management.json
  discovery/remotebuildexecution-v1.json
  discovery/remotebuildexecution-v1alpha.json
  discovery/remotebuildexecution-v2.json
  discovery/serviceconsumermanagement-v1.json
  discovery/serviceconsumermanagement-v1beta1.json
  discovery/servicecontrol-v1.json
  discovery/servicemanagement-v1.json
  discovery/servicenetworking-v1.json
  discovery/servicenetworking-v1beta.json
  discovery/serviceusage-v1.json
  discovery/serviceusage-v1beta1.json
  discovery/verifiedaccess-v1.json
  src/apis/appengine/v1.ts
  src/apis/appengine/v1beta.ts
  src/apis/binaryauthorization/v1.ts
  src/apis/cloudidentity/v1beta1.ts
  src/apis/cloudkms/v1.ts
  src/apis/composer/v1beta1.ts
  src/apis/content/v2.1.ts
  src/apis/dfareporting/v3.3.ts
  src/apis/dfareporting/v3.4.ts
  src/apis/displayvideo/v1.ts
  src/apis/remotebuildexecution/v1.ts
  src/apis/remotebuildexecution/v1alpha.ts
  src/apis/remotebuildexecution/v2.ts
  src/apis/serviceconsumermanagement/v1.ts
  src/apis/serviceconsumermanagement/v1beta1.ts
  src/apis/servicecontrol/v1.ts
  src/apis/servicemanagement/v1.ts
  src/apis/servicenetworking/v1.ts
  src/apis/servicenetworking/v1beta.ts
  src/apis/serviceusage/v1.ts
  src/apis/serviceusage/v1beta1.ts
  src/apis/verifiedaccess/v1.ts
Labels: cla: yes

#2127 build: add changelog generation
  package.json
  src/generator/download.ts
  src/generator/generate.ts
  src/generator/generator.ts
  src/generator/synth.ts
  test/test.synth.ts
Labels: cla: yes

#2185 refactor: do not require network access for unit tests
  src/googleapis.ts
  test/test.apikey.ts
  test/test.auth.ts
  test/test.clients.ts
  test/test.discover.ts
  test/test.drive.v2.ts
  test/test.media.ts
  test/test.options.ts
  test/test.path.ts
  test/test.query.ts
  test/test.synth.ts
  test/test.transporters.ts
  test/utils.ts
Labels: cla: yes

#2181 build: enable autodisco for generation
  .github/workflows/generator.yaml
  src/generator/docs.ts
  src/generator/download.ts
  src/generator/generator.ts
  src/generator/synth.ts
  synth.py
  test/test.docs.ts
  test/test.synth.ts
Labels: cla: yes

#2189 build: add repository dispatch trigger
  .github/workflows/generator.yaml
  src/generator/synth.ts
Labels: cla: yes

#2191 build: set git config before commit
  src/generator/synth.ts
Labels: cla: yes

#2192 build: improve logs, slice PR messages
  src/generator/synth.ts
Labels: cla: yes
