Repository googleapis/google-api-nodejs-client, pull requests merged in 2020-09, with the labels that each got.

#2344 build: delete blunderbuss
  .github/blunderbuss.yml
Labels: api: cloudbuild, cla: yes

#2362 fix: fixed compile error of invalid export
  src/index.ts
Labels: cla: yes

#2370 deps: update yargs-parser to latest
  package.json
Labels: automerge, cla: yes

#2371 build: update to latest build configuration
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
Labels: cla: yes
