Repository googleapis/google-api-nodejs-client, pull requests merged in 2020-04, with the labels that each got.

#2012 build: set AUTOSYNTH_MULTIPLE_COMMITS=true for context aware commits
  synth.py
Labels: automerge, cla: yes

#2013 build: update templates
  .eslintrc.json
  .github/workflows/ci.yaml
  .prettierrc.js
  synth.metadata
Labels: cla: yes

#2016 chore: remove duplicate mocha config
  .mocharc.json
Labels: automerge, cla: yes

#2017 fix: apache license URL (#468)
  .prettierrc.js
  synth.metadata
Labels: cla: yes

#2020 test: the kitchen sink system test sometimes times out
  system-test/kitchen.test.ts
Labels: cla: yes

#2021 chore(dep)!: deprecate node 8
  package.json
Labels: cla: yes

#2034 build: remove unused codecov config
  codecov.yaml
Labels: automerge, cla: yes

#2037 test: use discovery docs from fixture
  test/fixtures/discovery/blogger.json
  test/fixtures/discovery/drive.json
  test/test.apikey.ts
  test/test.auth.ts
  test/utils.ts
Labels: cla: yes

#2039 docs: update readme for drive readme
  samples/drive/README.md
Labels: automerge, cla: yes, kokoro:force-run

#2040 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#2042 chore: remove unused dev packages
  package.json
Labels: automerge, cla: yes

#2051 build: adopt CI codecov changes
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes

#2057 build: use a license template
  src/generator/templates/api-endpoint.njk
  src/generator/templates/api-index.njk
  src/generator/templates/index.njk
  src/generator/templates/license.njk
  src/generator/templates/root-index.njk
Labels: cla: yes

#2058 refactor: use local-auth for 3 legged samples
  samples/analytics/analytics.js
  samples/analyticsReporting/batchGet.js
  samples/blogger/insert.js
  samples/docs/create.js
  samples/docs/get.js
  samples/drive/download.js
  samples/drive/export.js
  samples/drive/list.js
  samples/drive/quickstart.js
  samples/drive/upload.js
  samples/gmail/labels.js
  samples/gmail/list.js
  samples/gmail/send.js
  samples/gmail/watch.js
  samples/jobs/jobs.js
  samples/mediaupload.js
  samples/mirror/mirror.js
  samples/package.json
  samples/people/contacts.js
  samples/people/me.js
  samples/sampleclient.js
  samples/sheets/append.js
  samples/sheets/insert-column.js
  samples/storage/README.md
  samples/test/test.samples.analyticsReporting.js
  samples/test/test.samples.blog.js
  samples/test/test.samples.docs.js
  samples/test/test.samples.drive.js
  samples/test/test.samples.gmail.js
  samples/test/test.samples.sheets.js
  samples/test/test.samples.webmasters.js
  samples/test/test.samples.youtube.js
  samples/webmasters/query.js
  samples/youtube/playlist.js
  samples/youtube/search.js
  samples/youtube/upload.js
Labels: automerge, cla: yes

#2061 build: add an ignore list to the generator
  ignore.json
  src/generator/generator.ts
Labels: automerge, cla: yes

#2064 chore: linting
  .mocharc.js
  .prettierrc.js
  samples/README.md
  synth.metadata
Labels: cla: yes

#2065 feat: add Blunderbussconfig
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#2071 Update blunderbuss.yml
  .github/blunderbuss.yml
Labels: automerge, cla: yes
