Repository googleapis/google-api-nodejs-client, pull requests merged in 2020-06, with the labels that each got.

#2198 docs: add a sample of using access token auth
  samples/accessTokenAuth.js
  samples/package.json
  samples/test/test.samples.auth.js
Labels: cla: yes

#2203 docs: update list of available samples
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#2199 docs: improve auth docs in the readme
  README.md
Labels: automerge, cla: yes

#2207 docs: update broken link on README
  README.md
  src/generator/synth.ts
Labels: cla: yes

#2220 build: try to use synth for the nightly run again
  .github/workflows/generator.yaml
  synth.py
Labels: automerge, cla: yes

#2245 build: disable docs test in CI
  package.json
Labels: cla: yes

#2244 fix: include compute in generated docs
  src/generator/docs.ts
Labels: cla: yes

#2242 feat: add disclaimers for services with GAPICs/Veneers
  disclaimers.json
  package.json
  src/apis/bigquery/README.md
  src/apis/bigquerydatatransfer/README.md
  src/apis/billingbudgets/README.md
  src/apis/cloudasset/README.md
  src/apis/cloudbilling/README.md
  src/apis/cloudbuild/README.md
  src/apis/clouddebugger/README.md
  src/apis/clouderrorreporting/README.md
  src/apis/cloudiot/README.md
  src/apis/cloudprofiler/README.md
  src/apis/cloudresourcemanager/README.md
  src/apis/cloudscheduler/README.md
  src/apis/cloudtrace/README.md
  src/apis/compute/README.md
  src/apis/container/README.md
  src/apis/containeranalysis/README.md
  src/apis/datacatalog/README.md
  src/apis/dataproc/README.md
  src/apis/datastore/README.md
  src/apis/dialogflow/README.md
  src/apis/dlp/README.md
  src/apis/dns/README.md
  src/apis/firestore/README.md
  src/apis/gameservices/README.md
  src/apis/jobs/README.md
  src/apis/language/README.md
  src/apis/logging/README.md
  src/apis/memcache/README.md
  src/apis/monitoring/README.md
  src/apis/osconfig/README.md
  src/apis/oslogin/README.md
  src/apis/pubsub/README.md
  src/apis/recommender/README.md
  src/apis/redis/README.md
  src/apis/runtimeconfig/README.md
  src/apis/secretmanager/README.md
  src/apis/securitycenter/README.md
  src/apis/servicedirectory/README.md
  src/apis/spanner/README.md
  src/apis/speech/README.md
  src/apis/tasks/README.md
  src/apis/texttospeech/README.md
  src/apis/translate/README.md
  src/apis/videointelligence/README.md
  src/apis/vision/README.md
  src/generator/disclaimer.ts
  src/generator/generator.ts
  src/generator/templates/README.md.njk
  synth.py
  test/test.clients.ts
  test/test.disclaimer.ts
  test/test.discover.ts
Labels: cla: yes

#2250 feat: export bundled types for TypeScript
  package.json
  src/generator/generate.ts
  src/generator/generator.ts
  src/generator/templates/root-index.njk
  src/index.ts
  test/test.index.ts
Labels: cla: yes
