Repository googleapis/google-api-nodejs-client, pull requests merged in 2021-06, with the labels that each got.

#2644 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: automerge, cla: yes

#2651 build: use GitHub Action for regeneration
  .github/workflows/update-apis.yaml
  src/generator/synth.ts
  synth.py
  test/test.synth.ts
Labels: cla: yes

#2659 build: update rules around throwing on deprecation
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: partial

#2664 build(node): do not throw on deprecation
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, context: full
