Repository googleapis/google-api-nodejs-client, pull requests merged in 2021-03, with the labels that each got.

#2538 build: increase memory for submit-prs
  package.json
Labels: cla: yes

#2539 build: fix spawn E2BIG in synth
  src/generator/synth.ts
Labels: cla: yes

#2545 test: temporary fix for flaky test related to mocha bug
  system-test/kitchen.test.ts
Labels: cla: yes

#2551 build: add release please autogeneration for config and manifest for mono-repo publishing
  .github/workflows/release-submodules.yaml
  .release-please-manifest.json
  release-please-config.json
  src/generator/generator.ts
Labels: cla: yes

#2552 Revert "test: temporary fix for flaky test related to mocha bug"
  system-test/kitchen.test.ts
Labels: cla: yes

#2559 build: generate root when building
  .release-please-manifest.json
  release-please-config.json
  src/generator/generator.ts
Labels: cla: yes

#2561 fix: add basic typescript sample and emit additional types
  README.md
  package.json
  samples/package.json
  samples/typescript/tsconfig.json
  samples/typescript/typescript.ts
Labels: cla: yes, samples

#2557 build: publish packages for each individual API
  .github/workflows/release.yaml
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  synth.py
Labels: cla: yes

#2569 chore: release
  .release-please-manifest.json
  CHANGELOG.md
  package.json
  samples/package.json
  src/apis/cloudtasks/CHANGELOG.md
  src/apis/cloudtasks/package.json
  src/apis/datafusion/CHANGELOG.md
  src/apis/datafusion/package.json
  src/apis/reseller/CHANGELOG.md
  src/apis/reseller/package.json
  src/apis/run/CHANGELOG.md
  src/apis/run/package.json
Labels: autorelease: pending, cla: yes

#2575 fix!: stop ignoring YouTube, and re-generate with latest API
  ignore.json
  samples/test/test.samples.youtube.js
  src/apis/youtube/v3.ts
  src/generator/generator.ts
  test/test.media.ts
Labels: cla: yes
