Repository googleapis/google-api-nodejs-client, pull requests merged in 2022-10, with the labels that each got.

#3086 build: pin prettier dependency (to fix release)
  package.json
Labels: size: xs

#3093 fix(deps): pin @types/prettier to v2.6.0
  package.json
Labels: automerge, size: xs

#3096 fix(build)!: update deps make Node 12 minimum
  src/apis/displayvideo/package.json
  src/generator/templates/package.json
Labels: size: s
